[report: archer_consolidated_report.csv]
source1 = /var/tables/views/consolidated_application_view.csv
source1_filters = ACTIVE = Y
source2 = /var/tables/consolidated_server_view.csv
output_path = /var/analysis

#[report: ais_report.csv]
#source1 = /var/tables/views/consolidated_application_view.csv
#source1_filters = ACTIVE = Y
#output_path = /var/analysis
#
#[report: ais_tables_raw.csv]
#source1 = /var/tables/applications.csv
#source1_filters = ACTIVE = Y
#source2 = /var/tables/condolidated_tools_pivot.csv
#source3 = /var/tables/consolidated_interfaces_table.csv
#source4 = /var/tables/staff_consolidated_pivot.csv
#source5 = /var/tables/databases.csv
#source6 = /var/tables/developmentsource_consolidated_pivot.csv
#source7 = /var/tables/serverinventories.csv
#output_path = /var/analysis

