; _vtx_origin = DEFAULT:usr/config/default/data_source_field_analysis.conf
[report: consolided_application_view.html]
source1 = C:\BTDM_7.1\var\tables\views\consolidated_application_view.csv
source1_filters = ACTIVE = Y
output_path = C:\BTDM_7.1\var\reporting

