_vtx:
  schema: v1
  kind: transform
  id: file_distribution_engine
  title: File Distribution Engine
  description: Base + Overlay distribution for interactive Excel files.
  owner: default
  version: 1.0.0
  tags:
  - interactive
  - overlay
  - distribution
  consumers:
  - usr/scripts/default/file_distribution_engine.py
  _vtx_origin: CUSTOM:usr/config/custom/file_distribution_engine.yaml
config:
  payload:
    jobs:
    - id: psdo_consolidated_apps_base_062302026
      enabled: true
      mode: base
      inputs:
      - var/tables/views/s5_migrations_consolidated_application_table_expanded_by_environment.csv
      outputs:
      - C:/Users/Jayson.Roberts/State of Maine/DAFS-MaineIT CCOE - Data Dog/Correlated_Data\CCoE_Inventory/migrations_application_view.xlsx
      tabs:
      - migrations_app_view
      sanitize_tabs: true
      anchor_columns:
      - ID
      - Environment
      file_format: xlsx
    - id: psdo_consolidated_applications_interactive_06302026
      enabled: true
      mode: interactive
      inputs:
      - C:/Users/Jayson.Roberts/State of Maine/DAFS-MaineIT CCOE - Data Dog/Correlated_Data\CCoE_Inventory/migrations_application_view.xlsx
      outputs:
      - var/interactive/data
      tabs:
      - migrations_app_view
      sanitize_tabs: true
      file_format: xlsx
  _vtx_origin: CUSTOM:usr/config/custom/file_distribution_engine.yaml
