; _vtx_origin = DEFAULT:usr/config/default/folder_cleanup.conf
[directory: C:\BTDM_7.1\var\logs]
file_age = 2

; _vtx_origin = DEFAULT:usr/config/default/folder_cleanup.conf
[directory: C:\Users\Jayson.Roberts\OneDrive - State of Maine\Documents\SOMReports]
file_age = 7

