; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\*Azure_Compute*.csv]
type = SDS
server_field = name
apply_transforms = reformat_default_sds
output_name = azure1.csv

; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\*Splunk_UF*.xlsx]
type = SDS
server_field = Hostname
apply_transforms = reformat_default_sds
output_name = splunk.csv

; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\SERVERS.csv]
type = SDS
server_field = SERVERNAME
apply_transforms = reformat_default_sds

; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\cmcc-rvtools.xlsx]
type = SDS
server_field = VM
apply_transforms = reformat_default_sds, reformat_rvtools
tabs = vInfo, vPartition

; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\risc-table*.csv]
type = SDS
server_field = Host Name
apply_transforms = reformat_default_sds
output_name = flexera.csv

; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\server_inventory*.csv]
type = SDS
server_field = SERVERNAME
rename_fields = APPLICATION:APPLICATION_perSI
apply_transforms = reformat_default_sds
output_name = serverinventories.csv

; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\server_inventory*.xlsx]
type = SDS
server_field = SERVERNAME
rename_fields = APPLICATION:APPLICATION_perSI
apply_transforms = reformat_default_sds
output_name = serverinventories.csv

; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\splunk_hostname.xlsx]
type = SDS
server_field = host
apply_transforms = reformat_default_sds

; _vtx_origin = DEFAULT:usr/config/default/monitor.conf
[monitor: C:\BTDM_7.1\var\customerdata\ssdc-rvtools.xlsx]
type = SDS
server_field = VM
apply_transforms = reformat_default_sds, reformat_rvtools
tabs = vInfo, vPartition

