reports:
- report_name: CMCC_rvtools_v_serverinventory
  source:
    file: C:\BTDM_7.1\var\tables\cmcc-rvtools_vinfo_server_audit.csv
    filter:
    - field: Powerstate
      operator: ==
      value: poweredOn
      _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
    key: Server
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  target:
    file: C:\BTDM_7.1\var\tables\serverinventories_sds.csv
    key: Server
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  comparison:
    type: difference
    direction: source_only
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  output:
    format: csv
    destination: C:\BTDM_7.1\var\reporting\cmcc_rvtools_vs_inventory_diff.csv
    include_row_data: true
    include_count_summary: true
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
- report_name: Applications_missing_servers
  source:
    file: C:\BTDM_7.1\var\tables\ccoe_consolidated_application_view.csv
    filter:
    - field: Server
      operator: isnull
      _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
    key: Server
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  target: null
  comparison:
    type: filter_only
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  output:
    format: csv
    destination: C:\BTDM_7.1\var\reporting\wsid_003_appsmissingservers.csv
    include_row_data: true
    include_count_summary: true
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
- report_name: count_with_application
  source:
    file: C:\BTDM_7.1\var\tables\ccoe_consolidated_application_view.csv
    filter:
    - field: Application
      operator: notnull
      _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  comparison:
    type: count
    count_type: total
    count_field: Applicatoin
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  output:
    format: html
    destination: C:\BTDM_7.1\var\reporting\apps_missing_servers.html
    include_count_summary: true
    include_row_data: false
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
- report_name: Applications_missing_Updaters
  source:
    file: C:\BTDM_7.1\var\tables\consolidated_application_view.csv
    filter:
    - field: ACTIVE
      operator: ==
      value: Y
      _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
    - field: Application Inventory Updater
      operator: isnull
      _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  comparison:
    type: count
    count_type: total
    count_field: Application
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  output:
    format: html
    destination: C:\BTDM_7.1\var\reporting\apps_missing_updaters.html
    include_row_data: false
    _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
  _vtx_origin: CUSTOM:usr/config/custom/reporting.yaml
