; _vtx_origin = CUSTOM:usr/config/custom/archer_data_source_analysis_conf.conf
[report: archer_consolidated_report.csv]
source1 = /var/tables/views/consolidated_application_view.csv
source1_filters = ACTIVE = Y
source2 = /var/tables/consolidated_server_view.csv
output_path = /var/analysis

