inventories:
- id: servers_core
  enabled: true
  output: var/tables/views/asset_inventory_servers.csv
  attributes:
  - Asset ID
  - Hostname
  - IP Address
  - OS
  - CPU
  - Memory GB
  - Storage GB
  - Source Winner
  match:
    keys:
    - Hostname
    - IP Address
    hostname_compare: shortname
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  sources:
  - id: ServerInventory
    enabled: true
    priority: 1
    prefix: SI
    path: var/tables/views/consolidated_server_view.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: SERVERNAME
      IP Address: IPADDRESS
      OS: TYPEOS
      CPU: VMPROCESSORS
      Memory GB: VMMEMORY
      Storage GB: VMSTORAGE
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  - id: SSDC_RVTools_vinfo
    enabled: true
    priority: 2
    prefix: SSDC_RVT_vinfo
    path: var/tables/ssdc-rvtools_vinfo_server_audit.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: VM
      IP Address: Primary IP Address
      OS: OS according to the VMware Tools
      CPU: CPUs
      Memory GB: Memory
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  - id: CMCC_RVTools_vinfo
    enabled: true
    priority: 3
    prefix: SSDC_RVT_vinfo
    path: var/tables/cmcc-rvtools_vinfo_server_audit.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: VM
      IP Address: Primary IP Address
      OS: OS according to the VMware Tools
      CPU: CPUs
      Memory GB: Memory
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  - id: SSDC_RVTools_vpartition
    enabled: true
    priority: 4
    prefix: SSDC_RVT_vinfo
    path: var/tables/ssdc-rvtools_vpartition_server_audit.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: Server
      Storage GB: used_(gb)
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  - id: CMCC_RVTools_vpartition
    enabled: true
    priority: 5
    prefix: SSDC_RVT_vinfo
    path: var/tables/cmcc-rvtools_vpartition_server_audit.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: Server
      Storage GB: used_(gb)
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  - id: insightvm
    enabled: true
    priority: 6
    prefix: R7IVM
    path: var/tables/insightvm.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: Asset Names
      IP Address: Asset IP Address
      OS: Asset OS Family
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  - id: flexera
    enabled: true
    priority: 7
    prefix: FLX
    path: var/tables/flexera.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: Host Name
      IP Address: IP Address
      OS: Device Type
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  - id: defender
    enabled: true
    priority: 7
    prefix: DEF
    path: var/tables/defender_serverinventory.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: DeviceName
      IP Address: null
      OS: OSPlatform
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  - id: splunk
    enabled: true
    priority: 8
    prefix: SPL
    path: var/tables/splunk.csv
    format: csv
    id_attribute: Hostname
    map:
      Hostname: Hostname
      IP Address: sourceIp
      OS: os
      _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
    _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
  _vtx_origin: CUSTOM:usr/config/custom/asset_inventory.yaml
