; _vtx_origin = CUSTOM:usr/config/custom/data_source_analysis_conf.conf
[report: consolidated_server_and_application_report.csv]
source1 = C:\BTDM_7.1\var\tables\views\consolidated_application_view.csv
source1_filters = ACTIVE = Y
source2 = C:\BTDM_7.1\var\tables\views\consolidated_server_view.csv
output_path = C:\BTDM_7.1\var\analysis

