; _vtx_origin = CUSTOM:usr/config/custom/data_source_analysis_reporting_old.conf
[report: archer_consolidated_server_and_application_report.csv]
dictionary_yaml = /usr/config/run/archer_data_source_analysis.yaml
source1 = /var/tables/views/consolidated_application_view.csv
source1_filters = ACTIVE = Y
source2 = /var/tables/views/consolidated_server_view.csv
output_path = /var/analysis

; _vtx_origin = CUSTOM:usr/config/custom/data_source_analysis_reporting_old.conf
[report: consolidated_server_and_application_report.csv]
dictionary_yaml = /usr/config/run/data_source_analysis.yaml
source1 = /var/tables/views/consolidated_application_view.csv
source1_filters = ACTIVE = Y
source2 = /var/tables/views/consolidated_server_view.csv
output_path = /var/analysis

