; _vtx_origin = CUSTOM:usr/config/custom/grc_data_source_analysis_visual.conf
[report: grc_data_source_analysis]
source1 = /opt/vtx/var/tables/views/consolidated_application_view.csv
source1_filters = ACTIVE = Y
source2 = /opt/vtx/var/tables/views/consolidated_server_view.csv
output_path = /opt/vtx/var/reporting

