stretches:
- name: ccoe_consolidated_application_view
  internal_csv: VTX_ROOT/var/tables/views/ccoe_consolidated_application_view.csv
  external_xlsx: C:\Users\Jayson.Roberts\State of Maine\DAFS-MaineIT CCOE - Data Dog\Correlated_Data\CCoE_Inventory\current\ccoe_consolidated_application_view.xlsx
  sheet_name: Sheet1
  key_columns:
  - ID
  xlsx_truncate_extra_rows: true
  xlsx_truncate_extra_cols: false
  _vtx_origin: CUSTOM:usr/config/custom/stretch_v2.yaml
- name: ccoe_consolidated_server_view
  internal_csv: VTX_ROOT/var/tables/views/ccoe_consolidated_server_view.csv
  external_xlsx: C:\Users\Jayson.Roberts\State of Maine\DAFS-MaineIT CCOE - Data Dog\Correlated_Data\CCoE_Inventory\current\ccoe_consolidated_server_view.xlsx
  sheet_name: Sheet1
  key_columns:
  - RECORDID
  xlsx_truncate_extra_rows: true
  xlsx_truncate_extra_cols: false
  _vtx_origin: CUSTOM:usr/config/custom/stretch_v2.yaml
